### ISSUE TITLE
Combine directories with only one child to make display more compact

### ISSUE THREAD

**Issue by tonycpsu** [jaypei/emacs-neotree#147] opened 2015-12-15 19:40 UTC
Sometimes (e.g. with Java projects) I'll be working in a deeply-nested directory structure where it would be nice to have directory paths collapsed.  `project-explorer` (another emacs tree package) does it, and it looks like this:

![tree comparison](http://i.imgur.com/Gt5i1fN.png)

(`project explorer` on the left, `neotree` on the right)

That's really nice because it keeps the indent level down.  I prefer a lot of other things about `neotree` (especially the `vc` integration) so I thought I'd ask how hard it would be to integrate this nice feature, which seems to happen in the compress-tree function [here](https://github.com/sabof/project-explorer/blob/master/project-explorer.el#L307).

**Comment by jaypei** [comment] 2016-01-30 16:06
Hi tonycpsu,

Thanks for the example, it will be a great feature.

Jay

**Comment by sound2gd** [comment] 2016-12-31 16:02
这个在写Java工程的时候很适用，希望楼主早点实现，感谢

**Comment by Abdisalan** [comment] 2023-08-11 04:42
Duplicate of #84

**Closed** 2023-08-11 04:44 UTC
Labels: enhancement
